### Oh My ZSH Config ###
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

### Variables ###
export PATH="$PATH:/home/$USER/.local/bin:/home/$USER/.local/bin/scripts"

### Aliases ###
# Shell
alias reset="source ~/.zshrc"

# Tmux
alias tmuxa="tmux attach-session -t"
alias tmuxn="tmux new-session -s"
alias tmuxk="tmux kill-session -t "

# Files
alias ls="lsd"
alias la="lsd -al"
alias ll="lsd -l"
alias lf="lsd -d */"

# Text
alias xcpy="xsel -ib"
alias xpst="xsel -ob"
alias xmty="xsel -cb"
alias vi="nvim"
alias vim"nvim"
alias clcat="sed 's/#.*//g' | sed '/^[[:space:]]*$/d'"

# Network
alias ipa="ip a sh wlp2s0 && ip a sh wg0 && sudo wg"
alias arpscan="sudo arp-scan --localnet"

# Download
alias yt-flac="yt-dlp -x --audio-format flac"

# Customization
alias ff="fastfetch"
