---

- name: Update system
  become: yes
  community.general.pacman:
    update_cache: yes
    upgrade: yes

- name: Install base programs and cli tools
  include_tasks: packages.yml

- name: Set system-wide settings
  include_tasks: system-settings.yml

- name: Deploy dotfiles
  include_tasks: dotfiles.yml
