---

- name: Create config folder
  file:
    path: /home/{{ local_user }}/.config/nvim
    state: directory
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
    mode: "0755"

- name: Install dependencies
  community.general.pacman:
    name:
      - lua-language-server
      - npm

- name: Get config from github
  become_user: "{{ local_user }}"
  git:
    repo: https://github.com/IkariTyux/neovim.git
    dest: /home/{{ local_user }}/.config/nvim

- name: Install packer
  become_user: "{{ local_user }}"
  git:
    repo: https://github.com/wbthomason/packer.nvim 
    dest: /home/{{ local_user }}/.local/share/nvim/site/pack/packer/start/packer.nvim
    depth: 1
