---

- name: Install neovim dependencies
  community.general.pacman:
    name:
      - lua-language-server
      - npm

- name: Install packer
  become_user: "{{ local_user }}"
  git:
    repo: https://github.com/wbthomason/packer.nvim 
    dest: /home/{{ local_user }}/.local/share/nvim/site/pack/packer/start/packer.nvim
    depth: 1

- name: Get Neovim config
  become_user: "{{ local_user }}"
  git:
    repo: git@github.com/IkariTyux/neovim.git
    dest: ~/.config/nvim 
