---

- name: Install all programs
  community.general.pacman:
    name:
      - bash-completion
      - kitty
      - tmux
      - lsd
      - vim
      - neovim
      - git
      - stow
      - curl
      - rsync
      - btop
      - htop
      - xsel
      - fastfetch
      - arp-scan
      - bind
      - traceroute
      - yt-dlp
      - man
      - tldr
      - unzip
      - gzip
      - imagemagick
      - nfs-utils
      - translate-shell
      - keyd
      - ttf-font-awesome
      - noto-fonts-cjk 
      - noto-fonts-emoji
      - noto-fonts
    state: present
