---

- name: Change shell
  command: usermod --shell /bin/zsh {{ local_user }}

- name: Install OMZ
  become_user: "{{ local_user }}"
  shell: rm -Rf ~/.oh-my-zsh && sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

- name: Install ZSH autosuggestions
  become_user: "{{ local_user }}"
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: /home/{{ local_user }}/.oh-my-zsh/plugins/zsh-autosuggestions

- name: Install ZSH syntax-highlighting
  become_user: "{{ local_user }}"
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: /home/{{ local_user }}/.oh-my-zsh/plugins/zsh-syntax-highlighting

- name: Install neovim dependencies
  community.general.pacman:
    name:
      - lua-language-server
      - npm

- name: Install packer
  become_user: "{{ local_user }}"
  git:
    repo: https://github.com/wbthomason/packer.nvim 
    dest: /home/{{ local_user }}/.local/share/nvim/site/pack/packer/start/packer.nvim
    depth: 1
