---

- name: Change shell
  user:
    name: "{{ local_user }}"
    shell: /bin/zsh

- name: Install OMZ
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

- name: Install ZSH autosuggestions
  become_user: "{{ local_user }}"
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: /home/{{ local_user }}/.oh-my-zsh/plugins/zsh-autosuggestions

- name: Install ZSH syntax-highlighting
  become_user: "{{ local_user }}"
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: /home/{{ local_user }}/.oh-my-zsh/plugins/zsh-syntax-highlighting

- name: Copy .zshrc
  copy:
    src: zshrc
    dest: /home/{{ local_user }}/.zshrc
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
    mode: "0755"

- name: Copy tmux config
  copy:
   src: tmux.conf
   dest: /home/{{ local_user }}/.tmux.conf
   owner: "{{ local_user }}"
   group: "{{ local_user }}"
   mode: "0755"

- name: Copy lsd config
  copy:
   src: lsd
   dest: /home/{{ local_user }}/.config
   owner: "{{ local_user }}"
   group: "{{ local_user }}"
   mode: "0755"

- name: Copy fastfetch config
  copy:
   src: fastfetch
   dest: /home/{{ local_user }}/.config
   owner: "{{ local_user }}"
   group: "{{ local_user }}"
   mode: "0755"
